version: "3.3"
services:
  lvdiscovery:
    build: .
    ports:
    - "8080:8080"
    environment:
      REDIS_URL: "redis://redis:6379"
  redis:
    image: redis:6.0-rc-alpine
    ports:
      - "6379:6379"
