name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        image_name: 'lvdiscovery'
        cache: true
        branch_tag: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
