name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/librevault/lvdiscovery/lvdiscovery:$(date +%s) --tag docker.pkg.github.com/librevault/lvdiscovery/lvdiscovery:latest
    - name: Publish the Docker package
      run: docker push docker.pkg.github.com/librevault/lvdiscovery/lvdiscovery:latest
