name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/librevault/lvdiscovery/lvdiscovery:$(date +%s) --tag docker.pkg.github.com/librevault/lvdiscovery/lvdiscovery:latest
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/librevault/lvdiscovery
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tags: docker.pkg.github.com/librevault/lvdiscovery/lvdiscovery:latest 
